[package]
name = "rust-sysctl-loader"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_sysctl_loader"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
